import React from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';

const Section = ({ title, children }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.5, delay: 0.1 }}
    className="mb-8"
  >
    <h2 className="text-2xl font-semibold mb-4 text-primary gradient-text">{title}</h2>
    <div className="space-y-3 text-muted-foreground leading-relaxed">
      {children}
    </div>
  </motion.div>
);

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-sky-100 dark:from-slate-900 dark:to-sky-950 flex flex-col pt-16 md:pt-20">
      <ScrollArea className="flex-grow">
        <main className="container mx-auto px-4 py-12 md:py-16 lg:py-20">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
          >
            <Card className="w-full max-w-4xl mx-auto rounded-2xl shadow-xl soft-shadow border-border overflow-hidden">
              <CardHeader className="bg-muted/30 p-6 sm:p-8 border-b">
                <div className="flex items-center space-x-3 mb-2">
                  <FileText className="h-8 w-8 text-primary" />
                  <CardTitle className="text-3xl md:text-4xl font-bold tracking-tight gradient-text">
                    Terms & Conditions
                  </CardTitle>
                </div>
                <p className="text-sm text-muted-foreground">Last Updated: May 30, 2025</p>
              </CardHeader>
              <CardContent className="p-6 sm:p-8 text-foreground">
                <Section title="1. Introduction">
                  <p>Welcome to FlowSyncAI ("we," "us," or "our"). FlowSyncAI is an AI-powered productivity platform designed to help individuals and teams manage tasks, collaborate, and enhance their workflow (the "Service"). These Terms and Conditions ("Terms") govern your access to and use of our website, applications, and services. By accessing or using FlowSyncAI, you agree to be bound by these Terms.</p>
                </Section>

                <Section title="2. User Responsibilities">
                  <p><strong>Acceptable Usage:</strong> You agree to use FlowSyncAI only for lawful purposes and in accordance with these Terms. You are responsible for all activities that occur under your account.</p>
                  <p><strong>Prohibited Behavior:</strong> You must not: (a) misuse our Service by knowingly introducing viruses, trojans, worms, or other material that is malicious or technologically harmful; (b) attempt to gain unauthorized access to our Service, the server on which our Service is stored, or any server, computer, or database connected to our Service; (c) use the Service to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights; (d) use the Service for any illegal activities or in violation of any applicable laws or regulations.</p>
                  <p><strong>Account Security:</strong> You are responsible for safeguarding your account credentials and for any activities or actions under your account. You agree to notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>
                </Section>

                <Section title="3. Intellectual Property">
                  <p>The Service and its original content (excluding Content provided by users), features, functionality, software, UI/UX, and codebase are and will remain the exclusive property of FlowSyncAI and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without billowing prior written consent of FlowSyncAI.</p>
                </Section>

                <Section title="4. AI & Automation Disclaimer">
                  <p>FlowSyncAI utilizes artificial intelligence and automation features to provide suggestions, summaries, and other assistance. While we strive for accuracy and usefulness, the results generated by these AI features may vary, may not always be accurate, complete, or suitable for your specific needs. You acknowledge that you are responsible for reviewing and verifying any AI-generated content or suggestions before relying on them. FlowSyncAI is not liable for any decisions made or actions taken based on the output of its AI features. Users are ultimately responsible for their final decisions and work products.</p>
                </Section>

                <Section title="5. Account Termination">
                  <p>We may terminate or suspend your access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or contact us for account deletion.</p>
                </Section>

                <Section title="6. Service Availability">
                  <p>We will use reasonable efforts to make the Service available 24/7, except for: (a) planned downtime (of which we shall give advance notice where practicable); or (b) any unavailability caused by circumstances beyond our reasonable control, including, for example, an act of God, act of government, flood, fire, earthquake, civil unrest, act of terror, strike or other labor problem (other than one involving Our employees), Internet service provider failure or delay, or denial of service attack.</p>
                  <p>We do not guarantee that the Service will always be available or be uninterrupted. We may suspend, withdraw, or restrict the availability of all or any part of our Service for business and operational reasons.</p>
                </Section>

                <Section title="7. Data Privacy & Security">
                  <p>Your privacy is important to us. Our collection and use of personal information in connection with the Service is described in our <Link to="/legal/privacy" className="text-primary hover:underline">Privacy Policy</Link>. We utilize Supabase for our backend infrastructure, which adheres to high security standards. By using FlowSyncAI, you agree to the collection and use of information in accordance with our Privacy Policy.</p>
                </Section>

                <Section title="8. Governing Law">
                  <p>These Terms shall be governed and construed in accordance with the laws of Bangladesh, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>
                </Section>

                <Section title="9. Changes to Terms">
                  <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
                </Section>

                <Section title="10. Contact Us">
                  <p>If you have any questions about these Terms, please contact us at <a href="mailto:legal@flowsync.ai" className="text-primary hover:underline">legal@flowsync.ai</a>.</p>
                </Section>
              </CardContent>
            </Card>
          </motion.div>
        </main>
      </ScrollArea>
    </div>
  );
};

export default TermsPage;